// Turns the single-file web build into a JS module the Expo app can import,
// so the whole game ships inside the app bundle and works offline.
// Run via `npm run build:app`.

import { readFileSync, writeFileSync } from 'node:fs';

const src = new URL('../mobile/web-build/index.html', import.meta.url);
const out = new URL('../mobile/game/gameHtml.ts', import.meta.url);

let html = readFileSync(src, 'utf8');
// Favicon, manifest and home-screen icon links are meaningless inside the app and would 404.
html = html.replace(/<link rel="(icon|manifest|apple-touch-icon)"[^>]*>\s*/g, '');

writeFileSync(
  out,
  `// GENERATED by scripts/embed-game.mjs from the web build. Do not edit.\n// Rebuild with \`npm run build:app\` in the project root.\nconst gameHtml: string = ${JSON.stringify(html)};\nexport default gameHtml;\n`,
);
console.log(`Embedded game: ${(html.length / 1024).toFixed(0)} KB -> mobile/game/gameHtml.ts`);
